### ISSUE TITLE
“bw” -Inaccurate

### ISSUE THREAD

**Issue by science2468** [MichaelPachec0/solusvm_api_sample#1]
Inaccurate traffic data conversion
![image](https://user-images.githubusercontent.com/102643084/219278283-7eae2764-d54d-4004-b079-d90bce3c4d06.png)
![image](https://user-images.githubusercontent.com/102643084/219278347-24b9296a-4644-46a5-8018-cb810c2fd9f6.png)

**Comment by MichaelPachec0** [comment]
thanks for reporting, just pushed #2 which fixes this.
